### ISSUE TITLE
Find Data source of Restaurants/Bars locations

### ISSUE THREAD

**Issue by ChristopheDuong** [IE-MBD-GroupB/Data-Challenge#4]
We need data sets of Bars and Restaurants locations

**Comment by Andr3sJ** [comment]
http://opendata.euskadi.eus/catalogo/-/restaurantes-sidrerias-bodegas/
Here's the link with the listof restaurants, bars and 'sidrerias'. It has name, description, street address, province, It has the API and it can be downloadedin different formats.

**Comment by ChristopheDuong** [comment]
Can you upload the data on the drive under "data challenge > data > others" ?

It would be great to find the lat/lon of these restaurants too (using some geocoding services or code)

Thanks

**Comment by Andr3sJ** [comment]
I just uploaded the data.
I still haven't been able to find better data than this one, but I'll keep
searching to see if we can get lat/lon as well.


On Fri, Feb 20, 2015 at 11:07 PM, Christophe Duong <notifications@github.com
